version: '3.8'

services:
  frontend:
    image: nlp-front-end
    build:
      context: ./ChatBot-FSTT-Front-End 
    ports:
      - "4200:4200"
    networks:
      - nlp-network

  backend:
    image: nlp-back-end
    build:
      context: ./api
    ports:
      - "8500:8500"
    networks:
      - nlp-network
    depends_on: 
      - chroma
  chroma: 
    image: chromadb/chroma
    container_name: chroma
    networks: 
     - nlp-network

networks:
  nlp-network:
    
